---
- name: 'Cache refresh'
  apt: 
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: true

- name: Upgrade all packages to the latest version
  apt: 
    upgrade: dist
    force_apt_get: true

- name: 'Apt Packages'
  apt:
    state: present
    force_apt_get: true
    name:
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - curl
      - git
      - gnupg2
      - iptables-persistent
      - jq
      - net-tools
      - nfs-common
      - openssh-client
      - openssh-server
      - openssl
      - python-setuptools
      - python3
      - python3-pip
      - python3-setuptools
      - python3-virtualenv
      - software-properties-common
      - sudo
      - tmux
      - unzip
      - vim
      - virtualenv
      - wget

- name: 'Check if /var/run/reboot-required exists'
  stat:
    path: /var/run/reboot-required
  register: reboot_required
  changed_when: false

#- name: 'Reboot needed'
#  add_host:
#    hostname: "{{ inventory_hostname }}"
#    groups: reboot_needed
- name: 'Reboot'
  reboot:
  when: reboot_required.stat.exists == True

